spring.application.name=api-gateway
server.port=8083

beneficiarios.service.url=http://localhost:8081
consulta.service.url=http://localhost:8082

spring.cloud.gateway.mvc.routes[0].id=beneficiarios-crud
spring.cloud.gateway.mvc.routes[0].uri=${beneficiarios.service.url}
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/beneficiarios/**
spring.cloud.gateway.mvc.routes[0].predicates[1]=Method=POST,PUT,DELETE

spring.cloud.gateway.mvc.routes[1].id=consulta-read
spring.cloud.gateway.mvc.routes[1].uri=${consulta.service.url}
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/consulta/**

